apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xgb-app
  template:
    metadata:
      labels:
        app: xgb-app
    spec:
      containers:
      - name: xgb-container
        image: 218736973000.dkr.ecr.eu-north-1.amazonaws.com/xgb-repo:latest
        ports:
        - containerPort: 5000

        # Health checks (important in real systems)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
